### PR TITLE
Added to JsonRpcError's Display impl

### PR DESCRIPTION
**Pull request by trevor-crypto**
Forgot this in the last PR :disappointed:

### CODE REVIEW

**Comment by thomaseizinger** [comment]
Do we want this in the Display impl? Given that this can be literally anything, I wouldn't want to Debug-print it otherwise it is going to completely blow up the error-stack (assuming this is used together with `anyhow` for example)

We can check if it is a `String` and optionally include that?

**Comment by trevor-crypto** [comment]
@thomaseizinger That's a good point. I'm ok with not including it, but do you know if there is a way for a user to get the value if needed?

**Comment by thomaseizinger** [comment]
> @thomaseizinger That's a good point. I'm ok with not including it, but do you know if there is a way for a user to get the value if needed?

The field is public so you can just read it! ie downcast if you are inside `anyhow` and happy days :)

But like I said, printing `data` if it is a string inside Display is fine with me.

**Comment by trevor-crypto** [comment]
Sweet, the downcasting seems fine to me. I'm not sure if it's even worth printing if it's a `String` since I have no idea if servers use this field as a String or an Object more... :man_shrugging:. Going to close, thanks!

**Pull request closed without merging**
